name: Vault Creation
on:
 workflow_dispatch:
    inputs:
      Team_Name:
        description: Terraform Workspaces
        required: false
        #default: devsecops-test
        type: choice
        options:
        - dso-sandbox
        - dso-test
        - devsecops-test
        - learning
        - devsecops
        - cloudops
        - kip-prod
        - kip-uat
        - conn-tech-sbox
        - tax-client
        - informatica
        - icas
        - culture-snap
        - pxcube
        - modelling
        - fmmicros
        - chrisastley
        - ukfmtis
        - tax-technology
        - enterprise-bey
        - digital-uk
        - ctc-portal
        - helios
        - btmobile
        - pccportal
        - tax-coe-b2c
        - fizznunwood
        - culture-snap-dev
        - kclientazure
      
      task:
        description: Task to be done 
        required: false
        #default: deploy
        type: choice
        options:
        - deploy

      Subscription_Name:
        description: Name of the Subscription
        required: false
        type: string

      Subscription_Id:
        description: Subscription Id
        required: true
        #type: number
      
      Tenant_Id:
        description: Tenant Id
        required: true
        #type: number

      
        
jobs:
  deploy:
    name: vault-creation
    runs-on: ubuntu-latest
    environment: vault-creation

    permissions:
      id-token: write
      contents: read
      pull-requests: write
      issues: write

    steps:
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Vault Token as env var
        run: |
          subscription_name=${{inputs.Subscription_Name}}
          subscription_id=${{inputs.Subscription_Id}}
          tenant_id=${{inputs.Tenant_Id}}
          team_name=${{inputs.Team_name}}
          region=${{inputs.region}}
          location=${{inputs.location}}
          echo "SUBSCRIPTION_NAME=$subscription_name" >> $GITHUB_ENV
          echo "SUBSCRIPTION_ID=$subscription_id" >> $GITHUB_ENV
          echo "TENANT_ID=$tenant_id" >> $GITHUB_ENV
          echo "TEAM_NAME=$team_name" >> $GITHUB_ENV
          echo "REGION=$region" >> $GITHUB_ENV
          echo "LOCATION=$location" >> $GITHUB_ENV
          echo "VAULT_TOKEN=$vault_token" >> $GITHUB_ENV
          echo "VAULT_ADDR=$vault_address" >> $GITHUB_ENV

          
      - name: Testing Json entry
        run: |
             echo "SUBSCRIPTION_NAME=$subscription_name" >> inputs.json




            
        
